apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

images:
  - name: service-api
    newName: service-api
    newTag: 2.0.0

replicas:
  - name: service-api
    count: 3

