apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

images:
  - name: service-api
    newName: service-api
    newTag: 1.0.0

replicas:
  - name: service-api
    count: 1

